# This is a basic workflow to help you get started with Actions
name: Terraform Azure Demo

on:
  workflow_dispatch:
   
env:
  ARM_CLIENT_ID: f35329b8-42ea-4ee9-bfb1-5caa244a284f       #It's specific to DEV. So need to replace it with appropriate value for each environment.
  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_DEV_CLIENT_SECRET}}  #It's specific to DEV. So need to replace it with appropriate value for each environment.
  ARM_SUBSCRIPTION_ID: 19e3a2a7-85c5-4f83-bf96-6c39488d079f
  ARM_TENANT_ID: cc7f83dd-bc5a-4682-9b3e-062a900202a2
  Terraform-RG-SUFFIX: DEV
  Terraform-RG: LEVOSHARED

jobs:
  main:
    name: 'Provision Main Infra'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v2
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.tf*"]'
      env:  #Below environment variables will be used in terraform scripts. So changing them will update the azure resource.
        Environment-Name: dev
        Environment-Name-Suffix: dev
        Environment-Name-Suffix-Short: dev
        Project-Name: anisshared
        Region-Short: eu
        Region: 'West Europe'
        ActiveDirectory-Tenant-Id: ${{ env.ARM_TENANT_ID }}
        Azure-Subscription-Id: ${{ env.ARM_SUBSCRIPTION_ID}} 
        Resource-Suffix: "001"
        Gateway-SKU-Name : 'Developer_1'
        Gateway-Publisher-Name: 'Mohd Anis'
        Gateway-Publisher-Email: 'mohdanis.mohdmokhtar@mattheyasia.com'
        Terraform-RG-SUFFIX: 'ANISRG'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan.bin --var-file=variables.tfvars -input=false

  apim:
    name: 'Add APIs,Policies to APIM'
    runs-on: ubuntu-latest
    needs: main
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.tf*"]'
      env:  #Below environment variables will be used in terraform scripts. So changing them will update the azure resource.
        Environment-Name: dev
        Environment-Name-Suffix: dev
        Environment-Name-Suffix-Short: dev
        Project-Name: anisshared
        Region-Short: eu
        Region: 'West Europe'
        Resource-Suffix: "001"
        Terraform-RG-SUFFIX: 'ANISRG'
        Basic-Auth-UserName: "test-user"
        Basic-Auth-Password: ${{ secrets.TF_FORMOX_DEV_BASICAUTH_PASSWORD }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan.bin --var-file=variables.tfvars -input=false -lock=false 
 




